#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-exactRankTests
Version  : 0.8.35
Release  : 2
URL      : https://cran.r-project.org/src/contrib/exactRankTests_0.8-35.tar.gz
Source0  : https://cran.r-project.org/src/contrib/exactRankTests_0.8-35.tar.gz
Summary  : Exact Distributions for Rank and Permutation Tests
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-exactRankTests-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
implementation of the Shift-Algorithm by Streitberg & Roehmel.

%package lib
Summary: lib components for the R-exactRankTests package.
Group: Libraries

%description lib
lib components for the R-exactRankTests package.


%prep
%setup -q -n exactRankTests

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713980301

%install
export SOURCE_DATE_EPOCH=1713980301
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/exactRankTests/DESCRIPTION
/usr/lib64/R/library/exactRankTests/INDEX
/usr/lib64/R/library/exactRankTests/Meta/Rd.rds
/usr/lib64/R/library/exactRankTests/Meta/data.rds
/usr/lib64/R/library/exactRankTests/Meta/features.rds
/usr/lib64/R/library/exactRankTests/Meta/hsearch.rds
/usr/lib64/R/library/exactRankTests/Meta/links.rds
/usr/lib64/R/library/exactRankTests/Meta/nsInfo.rds
/usr/lib64/R/library/exactRankTests/Meta/package.rds
/usr/lib64/R/library/exactRankTests/NAMESPACE
/usr/lib64/R/library/exactRankTests/NEWS
/usr/lib64/R/library/exactRankTests/R/exactRankTests
/usr/lib64/R/library/exactRankTests/R/exactRankTests.rdb
/usr/lib64/R/library/exactRankTests/R/exactRankTests.rdx
/usr/lib64/R/library/exactRankTests/data/ASAT.rda
/usr/lib64/R/library/exactRankTests/data/bloodp.rda
/usr/lib64/R/library/exactRankTests/data/ears.rda
/usr/lib64/R/library/exactRankTests/data/glioma.rda
/usr/lib64/R/library/exactRankTests/data/globulin.rda
/usr/lib64/R/library/exactRankTests/data/lungcancer.rda
/usr/lib64/R/library/exactRankTests/data/neuropathy.rda
/usr/lib64/R/library/exactRankTests/data/ocarcinoma.rda
/usr/lib64/R/library/exactRankTests/data/rotarod.rda
/usr/lib64/R/library/exactRankTests/data/sal.rda
/usr/lib64/R/library/exactRankTests/help/AnIndex
/usr/lib64/R/library/exactRankTests/help/aliases.rds
/usr/lib64/R/library/exactRankTests/help/exactRankTests.rdb
/usr/lib64/R/library/exactRankTests/help/exactRankTests.rdx
/usr/lib64/R/library/exactRankTests/help/paths.rds
/usr/lib64/R/library/exactRankTests/html/00Index.html
/usr/lib64/R/library/exactRankTests/html/R.css
/usr/lib64/R/library/exactRankTests/tests/Examples/exactRankTests-Ex.Rout.save
/usr/lib64/R/library/exactRankTests/tests/bugfix-tests.R
/usr/lib64/R/library/exactRankTests/tests/bugfix-tests.Rout.save
/usr/lib64/R/library/exactRankTests/tests/dtest.R
/usr/lib64/R/library/exactRankTests/tests/reg-tests.R
/usr/lib64/R/library/exactRankTests/tests/reg-tests.Rout.save
/usr/lib64/R/library/exactRankTests/tests/stest.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/exactRankTests/libs/exactRankTests.so
